version: '3.7'

services:
  api:
    container_name: flutter_api
    image: node:12.16.3
    depends_on:
      - mysql
    ports:
      - ${PORT}:${PORT}
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: '${MYSQL_HOST}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PW}'
      MYSQL_DB: '${MYSQL_DB}'

  mysql:
    container_name: sql_server
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    volumes:
      - flutter_project:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_PW}'
      MYSQL_DATABASE: '${MYSQL_DB}'

volumes:
  flutter_project:
